default: &my
  adapter: mysql
  encoding: utf8
  usernam: root
  password: root

development:
  <<: *my
  database: empresa

mysql:
  <<: *my
  database: empresa

postgres:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: empresa
  username: postgres
  password: postgres
  pool: 5

